# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2

project_name: warnly


builds:
  - builder: prebuilt
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    prebuilt:
      path: tmp/dist/warnly_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}{{ with .Arm64 }}_{{ . }}{{ end }}/warnly
    binary: warnly

sboms:
  - artifacts: archive

archives:
  - id: main
    name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto # enable rc releases (e.g. v1.0.0-rc.1)
  target_commitish: "{{ .Commit }}"

nightly:
  # Static main-nightly version for all nightly builds from main branch
  version_template: "main-nightly"

changelog:
  disable: true

dockers:
  - dockerfile: ./build/Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/vk-rv/warnly:{{ .Version }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - dockerfile: ./build/Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/vk-rv/warnly:{{ .Version }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "ghcr.io/vk-rv/warnly:{{ .Version }}"
    image_templates:
      - "ghcr.io/vk-rv/warnly:{{ .Version }}-amd64"
      - "ghcr.io/vk-rv/warnly:{{ .Version }}-arm64"
