# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
version: 2

project_name: warnly

git:
  tag_sort: semver

monorepo:
  tag_prefix: v

builds:
  - builder: prebuilt
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    prebuilt:
      path: tmp/dist/warnly_{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}{{ with .Arm64 }}_{{ . }}{{ end }}/warnly
    binary: warnly

sboms:
  - artifacts: archive

archives:
  - id: main
    name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto # enable rc releases (e.g. v1.0.0-rc.1)
  target_commitish: "{{ .Commit }}"
  footer: |
    ## Installation
    ### Docker Image :whale:
    ```bash
      docker pull ghcr.io/vk-rv/warnly:v{{ .Tag }}
    ```
    ## Thank you!
    We hope you :heart: this release! Feel free to open issues/discussions if you have any questions or feedback.
    - [Github Discussions](https://github.com/vk-rv/warnly/discussions)
    - [Github Issues](https://github.com/vk-rv/warnly/issues)
    - [Website](https://warnly.io)

changelog:
  use: github
  format: "{{.SHA}}: {{.Message}} (@{{.AuthorUsername}})"
  sort: asc
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Dependencies"
      regexp: '^.*?deps(\([[:word:]]+\))??!?:.+$'
      order: 999
    - title: "Other"
      order: 3

dockers:
  - dockerfile: ./build/Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/vk-rv/warnly:v{{ .Tag }}-amd64"
      - "ghcr.io/vk-rv/warnly:v{{ .Major }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  - dockerfile: ./build/Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/vk-rv/warnly:v{{ .Tag }}-arm64"
      - "ghcr.io/vk-rv/warnly:v{{ .Major }}-arm64"
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "ghcr.io/vk-rv/warnly:v{{ .Tag }}"
    image_templates:
      - "ghcr.io/vk-rv/warnly:v{{ .Tag }}-amd64"
      - "ghcr.io/vk-rv/warnly:v{{ .Tag }}-arm64"
  - name_template: "ghcr.io/vk-rv/warnly:v{{ .Major }}"
    image_templates:
      - "ghcr.io/vk-rv/warnly:v{{ .Major }}-amd64"
      - "ghcr.io/vk-rv/warnly:v{{ .Major }}-arm64"
