project_name: warnly
release:
  github:
    owner: vk-rv
    name: warnly
  name_template: '{{.Tag}}'
  prerelease: auto
  draft: false

builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ignore:
    - goos: windows
      goarch: arm64
  main: ./cmd/warnly
  ldflags: -s -w
  binary: warnly
  env:
    - CGO_ENABLED=0

archives:
  - id: warnly
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: tar.gz
    files:
    - LICENSE
    - README.md
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

dist: dist

dockers:
  - ids:
      - warnly
    goos: linux
    goarch: amd64
    dockerfile: build/Dockerfile
    image_templates:
    - "ghcr.io/vk-rv/warnly:{{ .Tag }}-amd64"
    - "ghcr.io/vk-rv/warnly:v{{ .Major }}-amd64"
    - "ghcr.io/vk-rv/warnly:v{{ .Major }}.{{ .Minor }}-amd64"
    - "ghcr.io/vk-rv/warnly:latest-amd64"
    use: buildx
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--platform=linux/amd64"
  - ids:
      - warnly
    goos: linux
    goarch: arm64
    dockerfile: build/Dockerfile
    image_templates:
    - "ghcr.io/vk-rv/warnly:{{ .Tag }}-arm64v8"
    - "ghcr.io/vk-rv/warnly:v{{ .Major }}-arm64v8"
    - "ghcr.io/vk-rv/warnly:v{{ .Major }}.{{ .Minor }}-arm64v8"
    - "ghcr.io/vk-rv/warnly:latest-arm64v8"
    use: buildx
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"
    - "--platform=linux/arm64/v8"

docker_manifests:
  - name_template: ghcr.io/vk-rv/warnly:{{ .Tag }}
    image_templates:
      - ghcr.io/vk-rv/warnly:{{ .Tag }}-arm64v8
      - ghcr.io/vk-rv/warnly:{{ .Tag }}-amd64
  - name_template: ghcr.io/vk-rv/warnly:v{{ .Major }}
    image_templates:
      - ghcr.io/vk-rv/warnly:v{{ .Major }}-arm64v8
      - ghcr.io/vk-rv/warnly:v{{ .Major }}-amd64
  - name_template: ghcr.io/vk-rv/warnly:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - ghcr.io/vk-rv/warnly:v{{ .Major }}.{{ .Minor }}-arm64v8
      - ghcr.io/vk-rv/warnly:v{{ .Major }}.{{ .Minor }}-amd64
  - name_template: ghcr.io/vk-rv/warnly:latest
    image_templates:
      - ghcr.io/vk-rv/warnly:latest-arm64v8
      - ghcr.io/vk-rv/warnly:latest-amd64
