FROM golang:1.25-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest
RUN go install github.com/a-h/templ/cmd/templ@latest
RUN go install mvdan.cc/gofumpt@latest
RUN apk add --no-cache make

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
