name: Lint
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  GO_VERSION: "1.25"

jobs:
  go-lint:
    name: "Lint Go"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0
          args: --verbose

  markdown-lint:
    name: "Lint Markdown"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          config: .markdownlint.yaml
          globs: |
            **/*.md
            !**/test/**/*

  go-mod-tidy:
    name: "Go Mod Tidy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Run go mod tidy.
        run: go mod tidy

      - name: Ensure clean git state.
        run: git diff-index --quiet HEAD -- || (echo "Please run 'go mod tidy' and commit changes." && exit 1)
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: golang/govulncheck-action@v1
        with:
          go-version-input: "1.25"
          go-package: ./...
          check-latest: true
