name: Release (Nightly)
on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"

permissions:
  contents: write
  packages: write

env:
  GO_VERSION: "1.25"

jobs:
  nightly-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: v2

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - name: Install GCC for arm64
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update && \
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: GoReleaser (Nightly) Build
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2.8.0"
          args: release --clean --nightly -f .goreleaser.${{ matrix.name }}.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: warnly-nightly-${{ matrix.name }}
          path: dist/warnly_${{ matrix.name }}_*/warnly

  nightly-release:
    runs-on: ubuntu-latest
    needs: nightly-build
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache: true

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: "${{ github.repository_owner }}"
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v5
        with:
          name: warnly-nightly-linux
          path: tmp/dist

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: GoReleaser (Nightly) Release
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2.8.0"
          args: release --nightly -f .goreleaser.nightly.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
